services:
  swarm-cronjob:
    runtime: runc
    labels:
      traefik.enable: false
    image: crazymax/swarm-cronjob
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=America/Sao_Paulo"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    deploy:
      placement:
        constraints:
          - node.role == manager
  build-aapanel:
    runtime: runc
    labels:
      traefik.enable: false
    image: docker
    command: > 
      /bin/sh /commands.sh
    env_file:
      - ./.env
    volumes:
      - './aapanel-ubuntu-22-04-sysbox:/aapanel-ubuntu-22-04-sysbox'
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./commands.sh:/commands.sh"
    deploy:
      mode: global
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 0 12 */7 * ?"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none