services:
  swarm-cronjob:
    runtime: runc
    image: crazymax/swarm-cronjob
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=America/Sao_Paulo"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    deploy:
      placement:
        constraints:
          - node.role == manager
  build-aapanel:
    runtime: runc
    image: docker
    command: > 
      /bin/sh -c "echo $$DOCKERHUB_PASS | docker login -u $$DOCKERHUB_USER --password-stdin && 
                  cd ./aapanel-ubuntu-22-04-sysbox && 
                  apk add make &&
                  make --no-print-directory mass_run &&
                  make --no-print-directory mass_update &&
                  make --no-print-directory mass_commit &&
                  make --no-print-directory mass_push &&
                  make --no-print-directory mass_rm
                  "
    env_file:
      - ./.env
    volumes:
      - './aapanel-ubuntu-22-04-sysbox:/aapanel-ubuntu-22-04-sysbox'
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: global
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 0 12 */7 * ?"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none