services:
  swarm-cronjob:
    image: crazymax/swarm-cronjob
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=America/Sao_Paulo"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    deploy:
      placement:
        constraints:
          - node.role == manager
  build-aapanel:
    image: docker
    command: > 
      /bin/sh -c "echo $$DOCKERHUB_PASS | docker login -u $$DOCKERHUB_USER --password-stdin && 
                  docker build -t antonio24073/aapanel:ubuntu-20-04-sysbox ./aapanel-ubuntu-20-04-sysbox/docker-file && 
                  docker push antonio24073/aapanel:ubuntu-20-04-sysbox &&
                  docker build -t antonio24073/aapanel:ubuntu-22-04-sysbox ./aapanel-ubuntu-22-04-sysbox/docker-file && 
                  docker push antonio24073/aapanel:ubuntu-22-04-sysbox
                  "
    env_file:
      - ./.env
    volumes:
      - './aapanel-ubuntu-20-04-sysbox/docker-file:/aapanel-ubuntu-20-04-sysbox/docker-file'
      - './aapanel-ubuntu-22-04-sysbox/docker-file:/aapanel-ubuntu-22-04-sysbox/docker-file'
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: global
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=0 0 12 */7 * ?"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none